[profile.default]
src = "contracts"
out = "out"
libs = ["../dependencies", "../shared", "../lib"]
solc = "0.8.19"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
local = "http://localhost:8545"
sepolia = "https://sepolia.infura.io/v3/6XJ6B1342MD2S4H1H3HTPVJ7Y2BZ6J7269"